### ISSUE TITLE
Cannot run `.` operator

### ISSUE THREAD

**Issue by XGHeaven** [jrainlau/canjs#1]
Here is an example

```js
const a = {}
a.b = 1
console.log(a.b)
```

Expected: 
```
1
```

Actual:
```
undefined
```

And more, Why you throw an error when setting a global variable?
https://github.com/jrainlau/canjs/blob/master/src/scope.js#L44

**Comment by jrainlau** [comment]
Thanks for your feedback!
It's acutually a bug and I've fixed it, you can reference it here:
![image](https://user-images.githubusercontent.com/12172868/49487357-fed7f880-f87c-11e8-9916-550dd4617f95.png)

The second question is "Why you throw an error when setting a global variable?"

In this interpreter, a variable is not a simple value but a `SimpleValue()` instance object. This instance provides a `set()` method for changing its value, it means that you can't set a value to a nonexistent object, and expression like `a = 1` is illegal but `var a = 1`.
