### ISSUE TITLE
和 new Function( ...args, code)(...values); 有什么区别吗

### ISSUE THREAD

**Issue by jasonHzq** [jrainlau/canjs#6]
和 new Function( ...args, code)(...values); 有什么区别吗

**Comment by linhuiw** [comment]
![image](https://image-static.segmentfault.com/438/089/438089835-5c0536c2c3bdf_articlex.gif)

**Comment by jasonHzq** [comment]
看到文章了，抱歉。原来是因为小程序的限制。
